import Head from "next/head";
import axios from "axios";
import ListItem from "../components/ListItem";
import { useEffect, useState } from "react";

export default function Home() {
  const [posts, setPosts] = useState([]);
  const getData = async () => {
    const res = await axios
      .get("https://jsonplaceholder.typicode.com/posts")
      .then((response) => {
        setPosts(response.data);
      });
  };
  useEffect(() => {
    getData();
  }, []);
  return (
    <div>
      <Head>
        <title>Vitrin Home Task</title>
        <meta name="keywords" content="web development programming" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>{posts.map(post => <ListItem 
      key={post.id}
      title={post.title}
      body={post.body}
      />

      )}</main>
    </div>
  );
}
